### ISSUE TITLE
Amélioration : Lieu des rencontres

### ISSUE THREAD

**Issue by hakimArfa** [Jolatorpille/IHCS#3]
Les lieux pour les rencontres sont fixé dans le constructeur du championnat.
Pouvoir le faire dans le main serait un bon ajout (plus flexible, et plus de liberté)
Solution: créer un attribut listLieu au championnat et passer une référence sur une liste en paramètre d'un autre constructeur. Ainsi si l'utilisateur ne souhaite pas créer cette liste il a toujours l'option par défaut (actuelle)

**Comment by Jolatorpille** [comment]
Cette amélioration a été effectuée à l'aide d'un tableau plutôt que d'une liste
