### ISSUE TITLE
Issu : multiple engagement

### ISSUE THREAD

**Issue by hakimArfa** [Jolatorpille/IHCS#4]
Problème: un même joueur peut être engager par plusieurs équipes. Il est même possible de 
créer une équipe complète en engageant cinq fois le même joueur.
Solution: Ajouter un attribut "free" dans la classe joueur. Un joueur ne peut être engager que si free est vrai. La classe équipe devra alors checker si le joueur peut être engagé.

**Comment by Jolatorpille** [comment]
Le problème a été réglé
